VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClientInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public sLastName As String
Public sFrstName As String
Public sMiddName As String
Public sSuffixNm As String
Public sBirthDte As String
Public sBirthPlc As String
Public sHouseNox As String
Public sAddresxx As String
Public sBarangay As String
Public sTownxxxx As String
Public sProvince As String
Public xAddressx As String
Public sMobileNo As String
Public sEmailAdd As String
Public sLTOIDxxx As String
Public sCitizenx As String
Public sTaxIDNox As String
Public sGenderCd As String
Public sFatherNm As String
Public sMotherNm As String
Public sOccptnNm As String
